defaults:
  - submitit_slurm

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 60
cpus_per_task: 16
gpus_per_node: 1
tasks_per_node: 1
mem_gb: 64
nodes: 1
partition: gpua100
name: ${hydra.job.name}
additional_parameters: {"mail-user": "florian.borchert@mattermost", "mail-type": "END,FAIL"}
  